// <auto-generated />
namespace WinFormsServiceStationApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Created3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Created3));
        
        string IMigrationMetadata.Id
        {
            get { return "202204071308260_Created3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
